name: 'Install Qt Dev Action'
description: 'Installs Qt modules using the online installer'
branding:
  color: 'green'
  icon: 'download-cloud'
inputs:
  packages:
    description: 'The desired packages to install'
    required: true
  timeout:
    description: 'The number of minutes after which the action automatically fails'
    required: false
    default: '10'
#outputs:
  #time: # id of output
    #description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'src/install_qt.js'
