name: 'Install Qt Dev Action'
description: 'Installs Qt modules using the online installer'
inputs:
  packages:
    description: 'The desired packages to install'
    required: true
#outputs:
  #time: # id of output
    #description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'install_qt.js'
